spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 5656qada
    url: jdbc:mysql://127.0.0.1/tkmybaits?characterEncoding=utf-8&useSSL=false


#mybatis:
#  mapper-locations: classpath*:sqlmapper/*Mapper.xml
#  basepackage: com.example.demo.dataobject.mybaitsTable
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql





#证书配置
#server:
#  port: 8443
#  ssl:
#    key-store: .keystore
#    key-store-password: 333333
#    key-store-type: JKS
#    key-alias: tomcat





# #属性值
#elasticsearch.ip: 127.0.0.1
#elasticsearch.port: 9300
#elasticsearch.pool: 5

#静态文件的默认路径
#spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#设置静态文件的路由访问前缀
#spring.mvc.static-path-pattern= /**


##启动时要执行的job，默认执行全部job
#spring.batch.job.name=job1,job2
##是否自动执行定义的job，默认是
#spring.batch.job.enabled=true
##是否初始化Spring Batch的数据库，默认为是
#spring.batch.initializer.enabled=true
#spring.batch.schema=
##设置Spring Batch的数据库表的前缀
#spring.batch.table-prefix=




