server:
  port: 8889
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 10s
        min-idle: 0
        max-idle: 8
merryyou:
  security:
    oauth2:
      storeType: jwt #redis
      jwtSigningKey: merryyou